In [1]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [2]:
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.andi.alquran.id',
    lang='id',  
    country='id', 
    sort=Sort.MOST_RELEVANT, 
    count=1000, 
    filter_score_with=None 
)

In [3]:
df = pd.DataFrame(np.array(result),columns=['review'])

df = df.join(pd.DataFrame(df.pop('review').tolist()))

df.head()

reviewId       userName  \
0  dcfe77d8-03c2-4135-87e1-f7115fa1d2ed     Lik Widodo   
1  f3ec6f3a-45a2-4214-99bd-f16b100dfeea   Hudan NafieX   
2  2d0d92cb-0a95-41d6-8b91-de988a271fcc    Dimas Bagus   
3  2e9ec233-3cb0-499d-9a44-59b4db67faa5  agus setiawan   
4  060903bb-5fb6-42ae-816e-3013a5a1232e    Zeppty Moza   

                                           userImage  \
0  https://play-lh.googleusercontent.com/a/ACg8oc...   
1  https://play-lh.googleusercontent.com/a-/ALV-U...   
2  https://play-lh.googleusercontent.com/a-/ALV-U...   
3  https://play-lh.googleusercontent.com/a-/ALV-U...   
4  https://play-lh.googleusercontent.com/a-/ALV-U...   

                                             content  score  thumbsUpCount  \
0  saya pakai hp dua, keduanya sy isi alquran ini...      5            777   
1  Ada saran dari saya coba sedikan option tombol...      5           1376   
2  Sudah bagus. Dengan terjemahan akurat, huruf h...      4            123   
3  Assalamualikum, Aplikasinya sudah bagus, cuman...      5           1598   
4  Terlalu sering update, padahal tampilan tidak ...      5           1102   

  reviewCreatedVersion                  at  \
0               2.7.97 2024-06-24 06:45:34   
1               2.7.93 2024-05-11 19:51:30   
2               2.7.97 2024-06-15 16:27:48   
3               2.7.97 2024-05-29 19:50:14   
4               2.7.96 2024-05-16 06:12:33   

                                        replyContent           repliedAt  \
0  Alhamdulillah, syukron katsiron Pak Widodo sud... 2019-03-22 16:23:17   
1                                               None                 NaT   
2  Assalamu'alaikum, Dimas Bagus.\nTerima kasih m... 2024-06-15 20:55:20   
3  Assalamu'alaikum, Agus Setiawan.\nTerima kasih... 2024-05-30 11:28:47   
4  Assalamu'alaikum, Zeppty Moza.\nTerima kasih m... 2024-05-16 10:57:40   

  appVersion  
0     2.7.97  
1     2.7.93  
2     2.7.97  
3     2.7.97  
4     2.7.96

In [4]:
df.shape

(1000, 11)

In [5]:
df[['userName', 'score','at', 'content']].head()

userName  score                  at  \
0     Lik Widodo      5 2024-06-24 06:45:34   
1   Hudan NafieX      5 2024-05-11 19:51:30   
2    Dimas Bagus      4 2024-06-15 16:27:48   
3  agus setiawan      5 2024-05-29 19:50:14   
4    Zeppty Moza      5 2024-05-16 06:12:33   

                                             content  
0  saya pakai hp dua, keduanya sy isi alquran ini...  
1  Ada saran dari saya coba sedikan option tombol...  
2  Sudah bagus. Dengan terjemahan akurat, huruf h...  
3  Assalamualikum, Aplikasinya sudah bagus, cuman...  
4  Terlalu sering update, padahal tampilan tidak ...

In [6]:
new_df = df[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False)
sorted_df.head()

userName  score                  at  \
488  Emal Maulana yosep      5 2024-07-19 20:54:25   
185           Mirza Bkl      5 2024-07-19 19:51:52   
391           Ahmad Zhr      5 2024-07-19 19:18:14   
191      ismail zam-zam      5 2024-07-19 18:59:39   
177      muhammad Husni      5 2024-07-19 18:32:32   

                                               content  
488  Alhamdulillah sangat bagus tulisan dan tajwid,...  
185  dengan adanya app ini membuat saya dgn mudah m...  
391  Dengan adanya aplikasi Al Qur'an Indonesia, ak...  
191  sangat mudah digunakan dan membantu belajar ta...  
177  dgn apk ini saya bisa lebih enak untuk baca al...

In [7]:
df_sentimen = sorted_df[['userName', 'score','at', 'content']] # simpan ke variabel df_sentimen

In [8]:
df_sentimen=df_sentimen[['content', 'score']]

In [9]:
df_sentimen.to_csv('sentimen_scraping.csv', index=False)

### Labeling Target

In [10]:
df_sentimen['score'].unique()

array([5, 3, 1, 4, 2])

Kriteria Sentimen :

- Score > 3 = 1
- Score = 3 = 0
- Score <= 2 -1

In [12]:
df_sentimen.head(20)

content  score
488  Alhamdulillah sangat bagus tulisan dan tajwid,...      5
185  dengan adanya app ini membuat saya dgn mudah m...      5
391  Dengan adanya aplikasi Al Qur'an Indonesia, ak...      5
191  sangat mudah digunakan dan membantu belajar ta...      5
177  dgn apk ini saya bisa lebih enak untuk baca al...      5
287  alhamdulillah, membuat baca Al Qur'an bisa kap...      5
550  utamakan perbaikan dalam sistem kadang2 bunyi ...      3
398  apk ini sngat membantu, sehingga dimnapun kta ...      5
520  oke .. sesuai.. cocok tingkatkan lagi pelayana...      5
293  alhamdulillah dengan aplikasi ini jadi bisa me...      5
8    assalamualaikum aplikasinya bagus, cuma kurang...      5
157  tidak banyak kata. Terimakasih buat yang membu...      5
173  Assalamualaikum wr Wb Kenapa kok yang bisa dit...      5
211  Alkhamdulillah dgn adanya aplikasi ini jadi me...      5
318  Wah, kok setelah di update, widget waktu shola...      3
182  sangat bermanfaat. alunan murottalnya indah da...      5
6    Aplikasinya jelek juga ternyata, diperbarui ve...      1
570  interface aplikasinya paling nyaman di antara ...      5
156  cocok untuk yang mau murajaah,atau pun ingin m...      5
607  sangat membantu untuk mengingatkan waktu shola...      5

In [13]:
def label(score):
  if score > 3:
    return 1
  elif score == 3 :
    return 0
  elif score <= 2 :
    return -1
df_sentimen['Label'] = df_sentimen ['score'].apply(label)
df_sentimen.head(20)

content  score  Label
488  Alhamdulillah sangat bagus tulisan dan tajwid,...      5      1
185  dengan adanya app ini membuat saya dgn mudah m...      5      1
391  Dengan adanya aplikasi Al Qur'an Indonesia, ak...      5      1
191  sangat mudah digunakan dan membantu belajar ta...      5      1
177  dgn apk ini saya bisa lebih enak untuk baca al...      5      1
287  alhamdulillah, membuat baca Al Qur'an bisa kap...      5      1
550  utamakan perbaikan dalam sistem kadang2 bunyi ...      3      0
398  apk ini sngat membantu, sehingga dimnapun kta ...      5      1
520  oke .. sesuai.. cocok tingkatkan lagi pelayana...      5      1
293  alhamdulillah dengan aplikasi ini jadi bisa me...      5      1
8    assalamualaikum aplikasinya bagus, cuma kurang...      5      1
157  tidak banyak kata. Terimakasih buat yang membu...      5      1
173  Assalamualaikum wr Wb Kenapa kok yang bisa dit...      5      1
211  Alkhamdulillah dgn adanya aplikasi ini jadi me...      5      1
318  Wah, kok setelah di update, widget waktu shola...      3      0
182  sangat bermanfaat. alunan murottalnya indah da...      5      1
6    Aplikasinya jelek juga ternyata, diperbarui ve...      1     -1
570  interface aplikasinya paling nyaman di antara ...      5      1
156  cocok untuk yang mau murajaah,atau pun ingin m...      5      1
607  sangat membantu untuk mengingatkan waktu shola...      5      1

### Check Missing Value

In [14]:
df_sentimen.isna().sum()

content    0
score      0
Label      0
dtype: int64

### Pre Processing

#### Case Folding

In [15]:
import re
df_sentimen['textCaseFolding'] = df_sentimen['content'].str.lower()  

In [16]:
pd.set_option('display.max_colwidth', None) 
df_sentimen.head()

content  \
488                                                                                           Alhamdulillah sangat bagus tulisan dan tajwid, terjemahan sangat jelas   
185  dengan adanya app ini membuat saya dgn mudah membaca di mana saja kapan saja....pokok nya memberi manfaat dan semoga menjadi jariah buat pencipta aplikasi ini🙏   
391                                                  Dengan adanya aplikasi Al Qur'an Indonesia, aku sungguh sangat terbantu, untuk membaca ayat ayat suci Al-Quran.   
191                                                              sangat mudah digunakan dan membantu belajar tajwid, untuk hafalan, melihat waktu shalat yang akurat   
177                           dgn apk ini saya bisa lebih enak untuk baca al Qur'an dan bisa saya baca kapan saya mau dan lebih baik di tambah penjelasan tajwid nya   

     score  Label  \
488      5      1   
185      5      1   
391      5      1   
191      5      1   
177      5      1   

                                                                                                                                                     textCaseFolding  
488                                                                                           alhamdulillah sangat bagus tulisan dan tajwid, terjemahan sangat jelas  
185  dengan adanya app ini membuat saya dgn mudah membaca di mana saja kapan saja....pokok nya memberi manfaat dan semoga menjadi jariah buat pencipta aplikasi ini🙏  
391                                                  dengan adanya aplikasi al qur'an indonesia, aku sungguh sangat terbantu, untuk membaca ayat ayat suci al-quran.  
191                                                              sangat mudah digunakan dan membantu belajar tajwid, untuk hafalan, melihat waktu shalat yang akurat  
177                           dgn apk ini saya bisa lebih enak untuk baca al qur'an dan bisa saya baca kapan saya mau dan lebih baik di tambah penjelasan tajwid nya

In [17]:
import warnings
warnings.filterwarnings("ignore")  
import nltk.corpus
nltk.download('stopwords')
from nltk.corpus import stopwords


stop = stopwords.words('indonesian')
df_sentimen['textStopWord'] = df_sentimen['textCaseFolding'].apply(lambda x:' '.join([word for word in x.split() if word not in (stop)]))
df_sentimen.head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/muhaiminnur/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


content  \
488                                                                                           Alhamdulillah sangat bagus tulisan dan tajwid, terjemahan sangat jelas   
185  dengan adanya app ini membuat saya dgn mudah membaca di mana saja kapan saja....pokok nya memberi manfaat dan semoga menjadi jariah buat pencipta aplikasi ini🙏   
391                                                  Dengan adanya aplikasi Al Qur'an Indonesia, aku sungguh sangat terbantu, untuk membaca ayat ayat suci Al-Quran.   
191                                                              sangat mudah digunakan dan membantu belajar tajwid, untuk hafalan, melihat waktu shalat yang akurat   
177                           dgn apk ini saya bisa lebih enak untuk baca al Qur'an dan bisa saya baca kapan saya mau dan lebih baik di tambah penjelasan tajwid nya   
287                                                                  alhamdulillah, membuat baca Al Qur'an bisa kapan saja. Lebih fleksibel dan memudahkan beribadah   
550                                                                               utamakan perbaikan dalam sistem kadang2 bunyi kadang tdk tuk Alquran is the best 👍   
398                                                         apk ini sngat membantu, sehingga dimnapun kta brada bisa membaca ataupun mendengar kan audio Al Qur'an..   
520                                                                                          oke .. sesuai.. cocok tingkatkan lagi pelayananan dan informasi lainnya   
293                         alhamdulillah dengan aplikasi ini jadi bisa membaca alquran di manapun berada... dan aplikasi sangat mudah dipahami... barakallah u fiik   

     score  Label  \
488      5      1   
185      5      1   
391      5      1   
191      5      1   
177      5      1   
287      5      1   
550      3      0   
398      5      1   
520      5      1   
293      5      1   

                                                                                                                                                     textCaseFolding  \
488                                                                                           alhamdulillah sangat bagus tulisan dan tajwid, terjemahan sangat jelas   
185  dengan adanya app ini membuat saya dgn mudah membaca di mana saja kapan saja....pokok nya memberi manfaat dan semoga menjadi jariah buat pencipta aplikasi ini🙏   
391                                                  dengan adanya aplikasi al qur'an indonesia, aku sungguh sangat terbantu, untuk membaca ayat ayat suci al-quran.   
191                                                              sangat mudah digunakan dan membantu belajar tajwid, untuk hafalan, melihat waktu shalat yang akurat   
177                           dgn apk ini saya bisa lebih enak untuk baca al qur'an dan bisa saya baca kapan saya mau dan lebih baik di tambah penjelasan tajwid nya   
287                                                                  alhamdulillah, membuat baca al qur'an bisa kapan saja. lebih fleksibel dan memudahkan beribadah   
550                                                                               utamakan perbaikan dalam sistem kadang2 bunyi kadang tdk tuk alquran is the best 👍   
398                                                         apk ini sngat membantu, sehingga dimnapun kta brada bisa membaca ataupun mendengar kan audio al qur'an..   
520                                                                                          oke .. sesuai.. cocok tingkatkan lagi pelayananan dan informasi lainnya   
293                         alhamdulillah dengan aplikasi ini jadi bisa membaca alquran di manapun berada... dan aplikasi sangat mudah dipahami... barakallah u fiik   

                                                                                              textStopWord  
488                                                         alhamdulillah bagus tulisan tajwid, terjemahan  
185      

In [18]:
import string 

# Fungsi untuk menghapus karakter spesial dari tweet
def remove_tweet_special(text):
    # Menghapus tab, new line, dan backslash
    text = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
    # Menghapus karakter non ASCII (emotikon, huruf Cina, dll.)
    text = text.encode('ascii', 'replace').decode('ascii')
    # Menghapus mention, link, dan hashtag
    text = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)", " ", text).split())
    # Menghapus URL yang tidak lengkap
    return text.replace("http://", " ").replace("https://", " ")

def remove_emoticons(text):  
    emoticon_pattern = r'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FB00-\U0001FBFF]+'  
    return re.sub(emoticon_pattern, '', text)  
                
df_sentimen['textClean'] = df_sentimen['content'].apply(remove_tweet_special)

# Fungsi untuk menghapus angka
def remove_number(text):
    return re.sub(r"\d+", "", text)

df_sentimen['textClean'] = df_sentimen['textStopWord'].apply(remove_number)

# Fungsi untuk menghapus tanda baca
def remove_punctuation(text):
    return text.translate(str.maketrans("", "", string.punctuation))

df_sentimen['textClean'] = df_sentimen['textStopWord'].apply(remove_punctuation)

# Fungsi untuk menghapus spasi di awal dan akhir
def remove_whitespace_LT(text):
    return text.strip()

df_sentimen['textClean'] = df_sentimen['textStopWord'].apply(remove_whitespace_LT)

# Fungsi untuk mengubah spasi ganda menjadi spasi tunggal
def remove_whitespace_multiple(text):
    return re.sub('\s+', ' ', text)

df_sentimen['textClean'] = df_sentimen['textStopWord'].apply(remove_whitespace_multiple)

# Fungsi untuk menghapus karakter tunggal
def remove_singl_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

df_sentimen['textClean'] = df_sentimen['textStopWord'].apply(remove_singl_char)
df_sentimen['textClean'] = df_sentimen['textStopWord'].apply(remove_emoticons)  

In [19]:
df_sentimen.head(20)

content  \
488                                                                                                                                                                                                                                                                                                         Alhamdulillah sangat bagus tulisan dan tajwid, terjemahan sangat jelas   
185                                                                                                                                                                                                                dengan adanya app ini membuat saya dgn mudah membaca di mana saja kapan saja....pokok nya memberi manfaat dan semoga menjadi jariah buat pencipta aplikasi ini🙏   
391                                                                                                                                                                                                                                                                Dengan adanya aplikasi Al Qur'an Indonesia, aku sungguh sangat terbantu, untuk membaca ayat ayat suci Al-Quran.   
191                                                                                                                                                                                                                                                                            sangat mudah digunakan dan membantu belajar tajwid, untuk hafalan, melihat waktu shalat yang akurat   
177                                                                                                                                                                                                                                         dgn apk ini saya bisa lebih enak untuk baca al Qur'an dan bisa saya baca kapan saya mau dan lebih baik di tambah penjelasan tajwid nya   
287                                                                                                                                                                                                                                                                                alhamdulillah, membuat baca Al Qur'an bisa kapan saja. Lebih fleksibel dan memudahkan beribadah   
550                                                                                                                                                                                                                                                                                             utamakan perbaikan dalam sistem kadang2 bunyi kadang tdk tuk Alquran is the best 👍   
398                                                                                                                                                                                                                                                                       apk ini sngat membantu, sehingga dimnapun kta brada bisa membaca ataupun mendengar kan audio Al Qur'an..   
520                                                                                                                                                                                                                                                                                                        oke .. sesuai.. cocok tingkatkan lagi pelayananan dan informasi lainnya   
293                                                                                                                                                                                                                                       alhamdulillah dengan aplikasi ini jadi bisa membaca alquran di manapun berada... dan aplikasi sangat mudah dipahami... barakallah u fiik   
8    assalamualaikum aplikasinya bagus, cuma kurangnya adalah fitur untuk mengubah qory di aplikasinya menurut saya agak ribet, jika mau mengganti harus kembali lagi ke pengaturan menurut saya agak ribet karena harus bolak balik, kalau bisa di tamba

In [20]:
import nltk 
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
df_sentimen['textTokens'] = df_sentimen['textClean'].apply(lambda x: word_tokenize(x))
df_sentimen.head()

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/muhaiminnur/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


content  \
488                                                                                           Alhamdulillah sangat bagus tulisan dan tajwid, terjemahan sangat jelas   
185  dengan adanya app ini membuat saya dgn mudah membaca di mana saja kapan saja....pokok nya memberi manfaat dan semoga menjadi jariah buat pencipta aplikasi ini🙏   
391                                                  Dengan adanya aplikasi Al Qur'an Indonesia, aku sungguh sangat terbantu, untuk membaca ayat ayat suci Al-Quran.   
191                                                              sangat mudah digunakan dan membantu belajar tajwid, untuk hafalan, melihat waktu shalat yang akurat   
177                           dgn apk ini saya bisa lebih enak untuk baca al Qur'an dan bisa saya baca kapan saya mau dan lebih baik di tambah penjelasan tajwid nya   

     score  Label  \
488      5      1   
185      5      1   
391      5      1   
191      5      1   
177      5      1   

                                                                                                                                                     textCaseFolding  \
488                                                                                           alhamdulillah sangat bagus tulisan dan tajwid, terjemahan sangat jelas   
185  dengan adanya app ini membuat saya dgn mudah membaca di mana saja kapan saja....pokok nya memberi manfaat dan semoga menjadi jariah buat pencipta aplikasi ini🙏   
391                                                  dengan adanya aplikasi al qur'an indonesia, aku sungguh sangat terbantu, untuk membaca ayat ayat suci al-quran.   
191                                                              sangat mudah digunakan dan membantu belajar tajwid, untuk hafalan, melihat waktu shalat yang akurat   
177                           dgn apk ini saya bisa lebih enak untuk baca al qur'an dan bisa saya baca kapan saya mau dan lebih baik di tambah penjelasan tajwid nya   

                                                                             textStopWord  \
488                                        alhamdulillah bagus tulisan tajwid, terjemahan   
185  app dgn mudah membaca saja....pokok nya manfaat semoga jariah pencipta aplikasi ini🙏   
391      aplikasi al qur'an indonesia, sungguh terbantu, membaca ayat ayat suci al-quran.   
191                                 mudah membantu belajar tajwid, hafalan, shalat akurat   
177                                dgn apk enak baca al qur'an baca penjelasan tajwid nya   

                                                                               textClean  \
488                                       alhamdulillah bagus tulisan tajwid, terjemahan   
185  app dgn mudah membaca saja....pokok nya manfaat semoga jariah pencipta aplikasi ini   
391     aplikasi al qur'an indonesia, sungguh terbantu, membaca ayat ayat suci al-quran.   
191                                mudah membantu belajar tajwid, hafalan, shalat akurat   
177                               dgn apk enak baca al qur'an baca penjelasan tajwid nya   

                                                                                               textTokens  
488                                                [alhamdulillah, bagus, tulisan, tajwid, ,, terjemahan]  
185  [app, dgn, mudah, membaca, saja, ...., pokok, nya, manfaat, semoga, jariah, pencipta, aplikasi, ini]  
391    [aplikasi, al, qur'an, indonesia, ,, sungguh, terbantu, ,, membaca, ayat, ayat, suci, al-quran, .]  
191                                     [mudah, membantu, belajar, tajwid, ,, hafalan, ,, shalat, akurat]  
177                                     [dgn, apk, enak, baca, al, qur'an, baca, penjelasan, tajwid, nya]

In [21]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [22]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# stemmed
def stemmed_wrapper(term):
    return stemmer.stem(term)

term_dict = {}
hitung=0

for document in df_sentimen['textTokens']:
    for term in document:
        if term not in term_dict:
            term_dict[term] = ' '
            
print(len(term_dict))
print("------------------------")
for term in term_dict:
    term_dict[term] = stemmed_wrapper(term)
    hitung+=1
    print(hitung,":",term,":" ,term_dict[term])

print(term_dict)
print("------------------------")

# apply stemmed term to dataframe
def get_stemmed_term(document):
    return [term_dict[term] for term in document]

df_sentimen['textSteam'] = df_sentimen['textTokens'].apply(lambda x:' '.join(get_stemmed_term(x)))
df_sentimen.head(20)

3561
------------------------
1 : alhamdulillah : alhamdulillah
2 : bagus : bagus
3 : tulisan : tulis
4 : tajwid : tajwid
5 : , : 
6 : terjemahan : terjemah
7 : app : app
8 : dgn : dgn
9 : mudah : mudah
10 : membaca : baca
11 : saja : saja
12 : .... : 
13 : pokok : pokok
14 : nya : nya
15 : manfaat : manfaat
16 : semoga : moga
17 : jariah : jariah
18 : pencipta : cipta
19 : aplikasi : aplikasi
20 : ini : ini
21 : al : al
22 : qur'an : qur an
23 : indonesia : indonesia
24 : sungguh : sungguh
25 : terbantu : bantu
26 : ayat : ayat
27 : suci : suci
28 : al-quran : al-quran
29 : . : 
30 : membantu : bantu
31 : belajar : ajar
32 : hafalan : hafal
33 : shalat : shalat
34 : akurat : akurat
35 : apk : apk
36 : enak : enak
37 : baca : baca
38 : penjelasan : jelas
39 : fleksibel : fleksibel
40 : memudahkan : mudah
41 : beribadah : ibadah
42 : utamakan : utama
43 : perbaikan : baik
44 : sistem : sistem
45 : kadang2 : kadang2
46 : bunyi : bunyi
47 : kadang : kadang
48 : tdk : tdk
49 : tuk : tuk
50

content  \
488                                                                                                                                                                                                                                                                                                         Alhamdulillah sangat bagus tulisan dan tajwid, terjemahan sangat jelas   
185                                                                                                                                                                                                                dengan adanya app ini membuat saya dgn mudah membaca di mana saja kapan saja....pokok nya memberi manfaat dan semoga menjadi jariah buat pencipta aplikasi ini🙏   
391                                                                                                                                                                                                                                                                Dengan adanya aplikasi Al Qur'an Indonesia, aku sungguh sangat terbantu, untuk membaca ayat ayat suci Al-Quran.   
191                                                                                                                                                                                                                                                                            sangat mudah digunakan dan membantu belajar tajwid, untuk hafalan, melihat waktu shalat yang akurat   
177                                                                                                                                                                                                                                         dgn apk ini saya bisa lebih enak untuk baca al Qur'an dan bisa saya baca kapan saya mau dan lebih baik di tambah penjelasan tajwid nya   
287                                                                                                                                                                                                                                                                                alhamdulillah, membuat baca Al Qur'an bisa kapan saja. Lebih fleksibel dan memudahkan beribadah   
550                                                                                                                                                                                                                                                                                             utamakan perbaikan dalam sistem kadang2 bunyi kadang tdk tuk Alquran is the best 👍   
398                                                                                                                                                                                                                                                                       apk ini sngat membantu, sehingga dimnapun kta brada bisa membaca ataupun mendengar kan audio Al Qur'an..   
520                                                                                                                                                                                                                                                                                                        oke .. sesuai.. cocok tingkatkan lagi pelayananan dan informasi lainnya   
293                                                                                                                                                                                                                                       alhamdulillah dengan aplikasi ini jadi bisa membaca alquran di manapun berada... dan aplikasi sangat mudah dipahami... barakallah u fiik   
8    assalamualaikum aplikasinya bagus, cuma kurangnya adalah fitur untuk mengubah qory di aplikasinya menurut saya agak ribet, jika mau mengganti harus kembali lagi ke pengaturan menurut saya agak ribet karena harus bolak balik, kalau bisa di tamba

In [23]:
df_sentimen.to_csv('hasil_TextPreProcessing.csv', index= False)

In [25]:
df_clean = pd.read_csv('hasil_TextPreProcessing.csv')

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_sentimen['textSteam'], df_sentimen['Label'], 
                                                    test_size = 0.20)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_train = tfidf_vectorizer.fit_transform(X_train)
tfidf_test = tfidf_vectorizer.transform(X_test)

In [28]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(800,)
(800,)
(200,)
(200,)


In [29]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorizer.fit(X_train)

CountVectorizer()

In [30]:
X_train = vectorizer.transform(X_train)
X_test = vectorizer.transform(X_test)

In [31]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(tfidf_train, y_train)

MultinomialNB()

In [32]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
y_pred = nb.predict(tfidf_test)

In [34]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

In [35]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score  
from sklearn.model_selection import train_test_split  
from sklearn.metrics import classification_report  
from sklearn.metrics import confusion_matrix  

clf = MultinomialNB()
clf.fit(X_train, y_train)
predicted = clf.predict(X_test)

print("MultinomialNB Accuracy:", accuracy_score(y_test, predicted))  
print("MultinomialNB Precision (macro):", precision_score(y_test, predicted, average="micro"))  
print("MultinomialNB Recall (macro):", recall_score(y_test, predicted, average="micro"))  
print("MultinomialNB f1_score (macro):", f1_score(y_test, predicted, average="micro"))  

print(f'Confusion Matrix:\n {confusion_matrix(y_test, predicted)}')  
print('====================================================\n')  
print(classification_report(y_test, predicted, zero_division=0))

MultinomialNB Accuracy: 0.785
MultinomialNB Precision (macro): 0.785
MultinomialNB Recall (macro): 0.785
MultinomialNB f1_score (macro): 0.785
Confusion Matrix:
 [[ 10   1   6]
 [ 10   0  12]
 [ 14   0 147]]

              precision    recall  f1-score   support

          -1       0.29      0.59      0.39        17
           0       0.00      0.00      0.00        22
           1       0.89      0.91      0.90       161

    accuracy                           0.79       200
   macro avg       0.40      0.50      0.43       200
weighted avg       0.74      0.79      0.76       200



In [36]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score  
from sklearn.model_selection import train_test_split  
from sklearn.metrics import classification_report  
from sklearn.metrics import confusion_matrix  
from sklearn.svm import SVC  # Import SVM classifier  

# Inisialisasi dan latih model SVM  
clf = SVC(kernel='linear')  # Anda bisa memilih kernel yang sesuai, misalnya 'linear', 'poly', 'rbf', dll.  
clf.fit(X_train, y_train)  
predicted = clf.predict(X_test)  

# Evaluasi performa model  
print("SVM Accuracy:", accuracy_score(y_test, predicted))  
print("SVM Precision (micro):", precision_score(y_test, predicted, average="micro"))  
print("SVM Recall (micro):", recall_score(y_test, predicted, average="micro"))  
print("SVM f1_score (micro):", f1_score(y_test, predicted, average="micro"))  

# Tampilkan confusion matrix  
print(f'Confusion Matrix:\n {confusion_matrix(y_test, predicted)}')  
print('====================================================\n')  
# Tampilkan classification report  
print(classification_report(y_test, predicted, zero_division=0))

SVM Accuracy: 0.805
SVM Precision (micro): 0.805
SVM Recall (micro): 0.805
SVM f1_score (micro): 0.805
Confusion Matrix:
 [[  7   3   7]
 [  9   2  11]
 [  6   3 152]]

              precision    recall  f1-score   support

          -1       0.32      0.41      0.36        17
           0       0.25      0.09      0.13        22
           1       0.89      0.94      0.92       161

    accuracy                           0.81       200
   macro avg       0.49      0.48      0.47       200
weighted avg       0.77      0.81      0.78       200

